import { Favourite, Station } from '@/types';

// TODO: replace with Supabase query
export const mockStations: Station[] = [
  {
    id: 'st-1',
    name: 'Shell Westlands',
    address: 'Waiyaki Way, Westlands',
    latitude: -1.2675,
    longitude: 36.8033,
    distanceKm: 1.2,
    status: 'open',
    amenities: ['ATM', 'Car Wash', 'Mini Mart'],
    prices: { petrol: 201.9, diesel: 188.4, super: 214.7 },
  },
  {
    id: 'st-2',
    name: 'TotalEnergies Kilimani',
    address: 'Argwings Kodhek Rd, Kilimani',
    latitude: -1.2921,
    longitude: 36.7814,
    distanceKm: 2.8,
    status: 'open',
    amenities: ['Coffee Shop', 'Tire Air'],
    prices: { petrol: 200.6, diesel: 187.8, super: 213.2 },
  },
  {
    id: 'st-3',
    name: 'Rubis Ngong Road',
    address: 'Ngong Rd, Adams Arcade',
    latitude: -1.3006,
    longitude: 36.7861,
    distanceKm: 3.1,
    status: 'closed',
    amenities: ['Mini Mart'],
    prices: { petrol: 199.5, diesel: 186.9, super: 212.4 },
  },
  {
    id: 'st-4',
    name: 'Ola Energy CBD',
    address: 'Haile Selassie Ave, CBD',
    latitude: -1.2864,
    longitude: 36.8233,
    distanceKm: 4.4,
    status: 'open',
    amenities: ['ATM'],
    prices: { petrol: 202.3, diesel: 189.1, super: 215.1 },
  },
  {
    id: 'st-5',
    name: 'Kenol Karen',
    address: 'Langata Rd, Karen',
    latitude: -1.3186,
    longitude: 36.7073,
    distanceKm: 6.8,
    status: 'open',
    amenities: ['Car Wash', 'Restaurant'],
    prices: { petrol: 198.9, diesel: 186.2, super: 211.9 },
  },
  {
    id: 'st-6',
    name: 'Shell Thika Road',
    address: 'Thika Superhighway, Roysambu',
    latitude: -1.2188,
    longitude: 36.8899,
    distanceKm: 8.2,
    status: 'open',
    amenities: ['EV Charger', 'Mini Mart'],
    prices: { petrol: 203.1, diesel: 189.6, super: 216.3 },
  },
  {
    id: 'st-7',
    name: 'TotalEnergies Upper Hill',
    address: 'Elgon Rd, Upper Hill',
    latitude: -1.3001,
    longitude: 36.8146,
    distanceKm: 5.3,
    status: 'closed',
    amenities: ['ATM', 'Coffee Shop'],
    prices: { petrol: 201.2, diesel: 188.2, super: 214.1 },
  },
  {
    id: 'st-8',
    name: 'Rubis Gigiri',
    address: 'UN Avenue, Gigiri',
    latitude: -1.2314,
    longitude: 36.8119,
    distanceKm: 7.1,
    status: 'open',
    amenities: ['Mini Mart', 'Tire Air'],
    prices: { petrol: 200.3, diesel: 187.3, super: 213.8 },
  },
];

// TODO: replace with Supabase query
export const mockFavourites: Favourite[] = [
  { id: 'fav-1', stationId: 'st-1' },
  { id: 'fav-2', stationId: 'st-5' },
  { id: 'fav-3', stationId: 'st-8' },
];
